Gestion Stagaires (Al Omrane)/Models/Profiles.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Stagaires__Al_Omrane_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profiles()
        {
            this.Stagaires = new HashSet<Stagaires>();
        }
        public int Id_P { get; set; }
        public string Libelle { get; set; }
        public string CV { get; set; }
        public string Experience { get; set; }
        public string Compétence { get; set; }
        public string ProjetRealisé { get; set; }
        public Nullable<int> Spés { get; set; }
    
        public virtual Spécialité Spécialité { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stagaires> Stagaires { get; set; }
    }
}

Gestion Stagaires (Al Omrane)/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gestion_Stagaires__Al_Omrane_.Models;

namespace Gestion_Stagaires__Al_Omrane_.Controllers
{
    public class ProfilesController : Controller
    {
        private Gestion_StagairesEntities db = new Gestion_StagairesEntities();

        public ActionResult Index()
        {
            if (Session["adm"] == null)
                return Redirect("/Login/Index");

            var profiles = db.Profiles.Include(p => p.Spécialité);
            return View(profiles.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profiles profiles = db.Profiles.Find(id);
            if (profiles == null)
            {
                return HttpNotFound();
            }
            return View(profiles);
        }

        public ActionResult Create()
        {
            if (Session["adm"] == null)
                return Redirect("/Login/Index");

            ViewBag.Spés = new SelectList(db.Spécialité, "Id_S", "Nom");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_P,CV,Libelle,Experience,Compétence,ProjetRealisé,Spés")] Profiles profiles)
        {
            string chemindoc = "";
            string chemindoc1 = "";
            string chemindoc2 = "";
            string chemindoc3 = "";
            HttpPostedFileBase file = Request.Files[0];
            HttpPostedFileBase file1 = Request.Files[1];
            HttpPostedFileBase file2 = Request.Files[2];
            HttpPostedFileBase file3 = Request.Files[3];

            if (file != null && file.ContentLength > 0)
            {
                chemindoc = Path.GetFileName(file.FileName);

                string dirdocs = Server.MapPath("~/Docs/");

                file.SaveAs(dirdocs + chemindoc);
            }
            if (file1 != null && file1.ContentLength > 0)
            {
                chemindoc1 = Path.GetFileName(file1.FileName);

                string dirdocs1 = Server.MapPath("~/Docs/");

                file1.SaveAs(dirdocs1 + chemindoc1);
            }
            if (file2 != null && file2.ContentLength > 0)
            {
                chemindoc2 = Path.GetFileName(file2.FileName);

                string dirdocs2 = Server.MapPath("~/Docs/");

                file2.SaveAs(dirdocs2 + chemindoc2);
            }
            if (file3 != null && file3.ContentLength > 0)
            {
                chemindoc3 = Path.GetFileName(file3.FileName);

                string dirdocs3 = Server.MapPath("~/Docs/");

                file3.SaveAs(dirdocs3 + chemindoc3);
            }
            if (ModelState.IsValid)
            {
                profiles.CV = chemindoc;
                profiles.Experience = chemindoc1;
                profiles.Compétence = chemindoc2;
                profiles.ProjetRealisé = chemindoc3;
                db.Profiles.Add(profiles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Spés = new SelectList(db.Spécialité, "Id_S", "Nom", profiles.Spés);
            return View(profiles);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profiles profiles = db.Profiles.Find(id);
            if (profiles == null)
            {
                return HttpNotFound();
            }
            ViewBag.Spés = new SelectList(db.Spécialité, "Id_S", "Nom", profiles.Spés);
            return View(profiles);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_P,Libelle,CV,Experience,Compétence,ProjetRealisé,Spés")] Profiles profiles)
        {
            Profiles p = db.Profiles.Find(profiles.Id_P);

            string chemindoc = "";
            string chemindoc1 = "";
            string chemindoc2 = "";
            string chemindoc3 = "";
            HttpPostedFileBase file = Request.Files[0];
            HttpPostedFileBase file1 = Request.Files[1];
            HttpPostedFileBase file2 = Request.Files[2];
            HttpPostedFileBase file3 = Request.Files[3];

            if (file != null && file.ContentLength > 0)
            {
                chemindoc = Path.GetFileName(file.FileName);

                string dirdocs = Server.MapPath("~/Docs/");

                file.SaveAs(dirdocs + chemindoc);
            }
            if (file1 != null && file1.ContentLength > 0)
            {
                chemindoc1 = Path.GetFileName(file1.FileName);

                string dirdocs1 = Server.MapPath("~/Docs/");

                file1.SaveAs(dirdocs1 + chemindoc1);
            }
            if (file2 != null && file2.ContentLength > 0)
            {
                chemindoc2 = Path.GetFileName(file2.FileName);

                string dirdocs2 = Server.MapPath("~/Docs/");

                file2.SaveAs(dirdocs2 + chemindoc2);
            }
            if (file3 != null && file3.ContentLength > 0)
            {
                chemindoc3 = Path.GetFileName(file3.FileName);

                string dirdocs3 = Server.MapPath("~/Docs/");

                file3.SaveAs(dirdocs3 + chemindoc3);
            }

            if (ModelState.IsValid)
            {
                if (!string.IsNullOrWhiteSpace(chemindoc)) p.CV = chemindoc;
                else p.CV = profiles.CV;

                if (!string.IsNullOrWhiteSpace(chemindoc1))  p.Experience = chemindoc1;
                else p.Experience = profiles.Experience;

                if (!string.IsNullOrWhiteSpace(chemindoc2)) p.Compétence = chemindoc2;
                else p.Compétence = profiles.Compétence;

                if (!string.IsNullOrWhiteSpace(chemindoc3)) p.ProjetRealisé = chemindoc3;
                else p.ProjetRealisé = profiles.ProjetRealisé;

                p.Libelle = profiles.Libelle;
                p.Spés = profiles.Spés;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Spés = new SelectList(db.Spécialité, "Id_S", "Nom", profiles.Spés);
            return View(profiles);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profiles profiles = db.Profiles.Find(id);
            if (profiles == null)
            {
                return HttpNotFound();
            }
            return View(profiles);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profiles profiles = db.Profiles.Find(id);
            db.Profiles.Remove(profiles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestion Stagaires (Al Omrane)/Views/Profiles/Create.cshtml
@model Gestion_Stagaires__Al_Omrane_.Models.Profiles

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Ajouter</h2>

@using (Html.BeginForm("Create", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
 {
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Profiles</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Charger Votre Doc", "CV", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Charger Votre Doc", "Experience", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Charger Votre Doc", "Compétence", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Charger Votre Doc", "ProjetRealisé", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Spés, "Spés", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Spés", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Spés, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Ajouter" class="btn btn-default" />
        </div>
    </div>
</div>
 }

<div>
    @Html.ActionLink("List Profiles", "Index")
</div>

Gestion Stagaires (Al Omrane)/Views/Profiles/Delete.cshtml
@model Gestion_Stagaires__Al_Omrane_.Models.Profiles

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

    <h3>Voulez vous vraiment supprimer @Model.Libelle ?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compétence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Compétence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjetRealisé)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjetRealisé)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Spécialité.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Spécialité.Nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("List Profiles", "Index")
        </div>
    }
</div>

Gestion Stagaires (Al Omrane)/Views/Profiles/Details.cshtml
@model Gestion_Stagaires__Al_Omrane_.Models.Profiles

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Details</h2>

<div>
    <h4>@Model.Libelle</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            <a href="~/Docs/@Model.CV"> CV </a>
            @*@Html.DisplayFor(model => model.CV)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            <a href="~/Docs/@Model.Experience"> Experience </a>
            @* @Html.DisplayFor(model => model.Experience) *@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Compétence)
        </dt>

        <dd>
            <a href="~/Docs/@Model.Compétence"> Compétence </a>
           @* @Html.DisplayFor(model => model.Compétence)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjetRealisé)
        </dt>

        <dd>
            <a href="~/Docs/@Model.ProjetRealisé"> ProjetRealisé </a>
            @*@Html.DisplayFor(model => model.ProjetRealisé)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Spécialité.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Spécialité.Nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modofier", "Edit", new { id = Model.Id_P }) |
    @Html.ActionLink("List Profiles", "Index")
</p>

Gestion Stagaires (Al Omrane)/Views/Profiles/Edit.cshtml
@model Gestion_Stagaires__Al_Omrane_.Models.Profiles

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

    <h2>Modifier @Model.Libelle</h2>

@using (Html.BeginForm("Edit", "Profiles", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_P)

        <div class="form-group">
            @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Charger Votre Doc", "CV", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Charger Votre Doc", "Experience", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Charger Votre Doc", "Compétence", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Charger Votre Doc", "ProjetRealisé", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Spés, "Spés", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Spés", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Spés, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvgarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("List Profiles", "Index")
</div>

Gestion Stagaires (Al Omrane)/Views/Profiles/Index.cshtml
@model IEnumerable<Gestion_Stagaires__Al_Omrane_.Models.Profiles>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nouveau Profile", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CV)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Experience)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Compétence)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjetRealisé)
        </th>
        <th>
            @Html.DisplayName("Spécialité")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CV)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Experience)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Compétence)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjetRealisé)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Spécialité.Nom)
            </td>
            <td>
                @Html.ActionLink("Modifier", "Edit", new { id = item.Id_P }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id_P }) |
                @Html.ActionLink("Supprimer", "Delete", new { id = item.Id_P })
            </td>
        </tr>
     }

</table>