Gestion Stagaires (Al Omrane)/Controllers/AffectationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using System.Windows.Forms;
using Gestion_Stagaires__Al_Omrane_.Models;

namespace Gestion_Stagaires__Al_Omrane_.Controllers
{
    public class AffectationController : Controller
    {
        private Gestion_StagairesEntities db = new Gestion_StagairesEntities();

        public ActionResult Index()
        {
            if (Session["adm"] == null)
                return Redirect("/Login/Index");

            var lists = db.Stagaires.Where(it => it.Date_Debut == null || it.S_Service == 0 || it.S_Service == null);
            return View(lists.ToList());
        }
        public ActionResult Chercher(string cin)
        {
            var liststg = db.Stagaires.Where(it => it.CIN == cin);

            return View("Index", liststg.ToList());
        }
        public ActionResult Affecter(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Stagaires stagaires = db.Stagaires.Find(id);
            if (stagaires == null)
            {
                return HttpNotFound();
            }

            ViewBag.Profil = new SelectList(db.Profiles, "Id_P", "Libelle", stagaires.Profil);
            ViewBag.S_Service = new SelectList(db.Services, "Numéro", "Nom", stagaires.S_Service);
            return View(stagaires);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Affecter([Bind(Include = "CIN,Date_Debut,Durée,Sujet,S_Service")] Stagaires stagaires)
        {
            Stagaires stg = db.Stagaires.Find(stagaires.CIN);
            if (ModelState.IsValid)
            {
                stg.Date_Debut = stagaires.Date_Debut;
                stg.Durée = stagaires.Durée;
                stg.Sujet = stagaires.Sujet;
                stg.S_Service = stagaires.S_Service;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Profil = new SelectList(db.Profiles, "Id_P", "Libelle", stagaires.Profil);
            ViewBag.S_Service = new SelectList(db.Services, "Numéro", "Nom", stagaires.S_Service);
            return View(stagaires);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestion Stagaires (Al Omrane)/Controllers/FinStageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gestion_Stagaires__Al_Omrane_.Models;

namespace Gestion_Stagaires__Al_Omrane_.Controllers
{
    public class FinStageController : Controller
    {
        private Gestion_StagairesEntities db = new Gestion_StagairesEntities();

        public ActionResult Index()
        {
            if (Session["adm"] == null)
                return Redirect("/Login/Index");

            var stagaires = db.Stagaires;
            List<Stagaires> stg = new List<Stagaires>();
            foreach(var it in stagaires)
            {
                if (it.Date_Debut!=null && it.Durée!=null)
                {
                    int d = int.Parse(it.Durée[0].ToString());
                    TimeSpan dif = ((TimeSpan)(it.Date_Debut- DateTime.Now));
                
                    if ((dif.Days >= 30 && d==1) || (dif.Days >= 60 && d == 2) || (dif.Days >= 90 && d == 3) || (dif.Days >= 120 && d == 4) || (dif.Days >= 150 && d == 5) || (dif.Days >= 180 && d == 6))
                    {
                        stg.Add(it);
                    }
                }
            }
            return View(stg.OrderBy(it=>it.Date_Debut).ToList());
        }

        public ActionResult Chercher(string cin)
        {
            var liststg = db.Stagaires.Where(it => it.CIN == cin);

            return View("Index", liststg.ToList());
        }

        public ActionResult Modifier(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stagaires stagaires = db.Stagaires.Find(id);
            if (stagaires == null)
            {
                return HttpNotFound();
            }
            ViewBag.Profil = new SelectList(db.Profiles, "Id_P", "Libelle", stagaires.Profil);
            ViewBag.S_Service = new SelectList(db.Services, "Numéro", "Nom", stagaires.S_Service);
            return View(stagaires);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modifier([Bind(Include = "CIN,Rapport,Depos_Rappoert,Note")] Stagaires stagaires)
        {
            string chemindoc = "";

            HttpPostedFileBase file = Request.Files[0];

            if (file != null && file.ContentLength > 0)
            {
                chemindoc = Path.GetFileName(file.FileName);

                string dirdocs = Server.MapPath("~/Docs/");

                file.SaveAs(dirdocs + chemindoc);
            }

            Stagaires stg = db.Stagaires.Find(stagaires.CIN);
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrWhiteSpace(chemindoc))
                {
                    stg.Depos_Rappoert = true;
                }
                stg.Rapport = chemindoc;
                stg.Note = stagaires.Note;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Profil = new SelectList(db.Profiles, "Id_P", "Libelle", stagaires.Profil);
            ViewBag.S_Service = new SelectList(db.Services, "Numéro", "Nom", stagaires.S_Service);
            return View(stagaires);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestion Stagaires (Al Omrane)/Views/FinStage/Index.cshtml
@model IEnumerable<Gestion_Stagaires__Al_Omrane_.Models.Stagaires>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

    <h2>List des stagiaires qui ont terminé</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="srch">
    @using (Html.BeginForm("Chercher", "Affectation", FormMethod.Get))
     {
        @Html.Label("Recherch par CIN :")
        @Html.TextBox("cin")
        <input type="submit" value="Chercher" />
     }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prenom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Debut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Durée)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Sujet)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profiles.Spécialité)
        </th>
        <th>
            @Html.DisplayName("Service")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Debut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Durée)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sujet)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.Profiles.Spécialité.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Services.Nom)
            </td>
            <td>
               | @Html.ActionLink("Dernier etape", "Modifier", new { id=item.CIN }) |
            </td>
        </tr>
     }

</table>

Gestion Stagaires (Al Omrane)/Views/FinStage/Modifier.cshtml
@model Gestion_Stagaires__Al_Omrane_.Models.Stagaires

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>@Model.Nom @Model.Prenom</h2>

 @using (Html.BeginForm("Modifier", "FinStage", FormMethod.Post, new { enctype = "multipart/form-data" }))
  {
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CIN)

    <div class="form-group">
        @Html.Label("Charger Votre Doc", "Rapport", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="doc" id="doc" accept="file_extention|.pdf,.doc,.docx" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Depos_Rappoert, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Depos_Rappoert)
                @Html.ValidationMessageFor(model => model.Depos_Rappoert, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
  }

<div>
    @Html.ActionLink("List Stagaires", "Index")
</div>